# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mpcflushesc <- function(data, nevents) {
    .Call('TSLib_mpcflushesc', PACKAGE = 'TSLib', data, nevents)
}

mpc2tecc <- function(mpc, nevents, resolution) {
    .Call('TSLib_mpc2tecc', PACKAGE = 'TSLib', mpc, nevents, resolution)
}

rasterc <- function(events, pattern, event_count) {
    .Call('TSLib_rasterc', PACKAGE = 'TSLib', events, pattern, event_count)
}

trialdefc <- function(events, pattern, event_count, pattern_count) {
    .Call('TSLib_trialdefc', PACKAGE = 'TSLib', events, pattern, event_count, pattern_count)
}

