#' Creates an active experiment given the critical files
#'
#' @param name The name of the experiment (e.g., "Consistent Weber)
#' @param dropbox The dropbox path
#' @param conditionsFile The conditions file path
#' @param protocolFile The protocol file path
#' @param eventcodesFile The eventcodes file path
#' @return NULL (creates the experiment directory structure)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateActiveExperiment <- function(name, dropbox, conditionsFile, protocolFile, eventcodesFile=NULL){

  experiment = ExperimentID(basename(protocolFile))
  experimentFolderName = tolower(paste0(experiment, "_", gsub(" ", "_", name)))
  experimentFolder = file.path(dropbox, experimentFolderName)

  # First create the directories...
  dirs <- list(file.path(experimentFolder, 'experiment'),
               file.path(experimentFolder, 'analysis', 'tables'),
               file.path(experimentFolder, 'analysis', 'figures'),
               file.path(experimentFolder, 'analysis', 'scripts', 'stan'),
               file.path(experimentFolder, 'data', 'mpc'),
               file.path(experimentFolder, 'docs', 'manuscript'))
  purrr::map(dirs, dir.create, recursive=TRUE)

  # Create the new files
  CreateAnalysisFile(file.path(experimentFolder, "analysis", paste0(experiment, "_main.R")))
  CreateAnalysisFile(file.path(experimentFolder, "analysis", paste0(experiment, "_daily.R")))
  CreateAnalysisFile(file.path(experimentFolder, "analysis", "scripts", paste0(experiment, "_functions.R")))
  CreateManuscriptFile(file.path(experimentFolder, "docs", "manuscript", paste0(experiment, "_manuscript.Rmd")))
  CreateJSON(experimentFolder,
             conditionsFile,
             protocolFile,
             eventcodesFile,
             file.path(experimentFolder, "data", paste0(experiment, "_dataset.json")))

  # Now move the three critical files...
  files <- list(eventcodesFile, protocolFile, conditionsFile)
  new_location <- file.path(dropbox,
                            experimentFolderName,
                            'experiment',
                            basename(c(eventcodesFile, protocolFile, conditionsFile)))
  purrr::map2(files, new_location, file.rename)

  # Lastly, create the Rproj file
  CreateRproj(file.path(experimentFolder, paste0(experimentFolderName, '.Rproj')))
}

#' Creates an active experiment given the critical files
#'
#' @param file The filename of the new analysis file (e.g., ~/Desktop/h_main.R)
#' @return NULL (creates the analysis file)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateAnalysisFile <- function(file){

  base_file <- basename(file)
  ismain <- strsplit(base_file, '_')[[1]][2] %in% c('main.R', 'daily.R')

  lines <- c(sprintf('# Name   : %s', base_file),
             sprintf('# Author : '),
             sprintf('# Date   : %s', format(Sys.Date(), '%Y.%m.%d')),
             sprintf('# Purpose: '),
             sprintf('# '),
             sprintf('# '),
             sprintf('# CHANGELOG '),
             sprintf('# --------- '),
             sprintf('# %s. Automatically generated by TSExperiment', format(Sys.Date(), '%Y.%m.%d')),
             sprintf(' '),
             sprintf(' '),
             ifelse(ismain, 'library(magrittr)', ''),
             ifelse(ismain, 'library(tidyverse)', ''),
             ifelse(ismain, 'library(TSLib)', ''),
             ifelse(ismain, ' ', ''),
             ifelse(ismain, "source('analysis/scripts/%s_functions.R')", ""))

  writeLines(lines, con = file)
}

#' Creates the manuscript's main Markdown file
#'
#' @param file The filename of the new manuscript file (e.g., ~/Dropbox/Active/h_consisten_weber/manuscript/h_main.md)
#' @return NULL (creates the markdown file)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateManuscriptFile <- function(file){
  lines <- c('---',
             "title      : 'title'",
             "shorttitle : 'running head'",
             " ",
             " ",
             "author: ",
             "  - name          : 'David M. Freestone'",
             "    affiliation   : '1'",
             "    corresponding : yes    # Define only one corresponding author",
             "    address       : '300 Pompton Rd, Wayne NJ 07470'",
             "    email         : 'freestoned@wpunj.edu'",
             " ",
             "affiliation: ",
             "  - id           : '1'",
             "    institution      : 'William Paterson University'",
             " ",
             " ",
             "author_note: |",
             "   Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.",
             "   Enter author note here.",
             " ",
             " ",
             "abstract: | ",
             "  Enter abstract here. Each new line herein must be indented, like this line.",
             " ",
             " ",
             "keywords          : 'keywords'",
             "wordcount         : ''",
             " ",
             '# Uncomment this and include the location of the bibliography',
             "# bibliography      : ['references.bib']",
             " ",
             "figsintext        : no",
             "figurelist        : no",
             "tablelist         : no",
             "footnotelist      : no",
             "lineno            : yes",
             "mask              : no",
             " ",
             "class             : 'man'",
             "output            : papaja::apa6_pdf",
             " ",
             " ",
             sprintf('# %s. Automatically generated by TSExperiment', format(Sys.Date(), '%Y.%m.%d')),
             "---",
             " ",
             " ",
             "```{r setup, include = FALSE}",
             "     knitr::opts_chunk$set(out.width='50%', fig.align = 'center', dpi=1200)",
             "     library('papaja')",
             "```")
  writeLines(lines, con = file)
}

#' Creates an active experiment given the critical files
#'
#' @param file The filename of the new analysis file (e.g., ~/Desktop/h_main.R)
#' @return NULL (creates the analysis file)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateJSON <- function(experimentFolder, conditionsFile, protocolFile, eventcodesFile, dataFile){

  experiment = ExperimentID(basename(protocolFile))
  conditions <- readr::read_tsv(conditionsFile)
 lines <- list(principle_investigator = conditions$Lab[1],
               location = conditions$Location[1],
               purpose = conditions$Purpose[1],
               equipment = list(hardware = conditions$Hardware[1],
                                software = conditions$Software[1]),
               subjects = list(n = length(conditions$Mouse),
                               IDs = conditions$Mouse,
                               species = conditions$Species,
                               strain = conditions$Strain,
                               sex = conditions$Sex,
                               supplier = conditions$Supplier),
               # TODO(David): Add standard event codes...
               conditions = list(file = basename(conditionsFile),
                                 contents = readLines(conditionsFile)),
               events = list(files = basename(c(eventcodesFile)),
                             contents = readLines(eventcodesFile)),
               # TODO(David): What if there's more than one protocol?
               protocol = list(file = conditions$Protocol[1],
                               contents = readLines(protocolFile)),
               analysis = list(main = readLines(file.path(experimentFolder, "analysis", paste0(experiment, "_main.R"))),
                               functions = readLines(file.path(experimentFolder, "analysis", paste0(experiment, "_daily.R"))),
                               daily = readLines(file.path(experimentFolder, "analysis", "scripts", paste0(experiment, "_functions.R")))),
               data = list(files = NA,
                           data = NA))

 writeLines(jsonlite::toJSON(lines, pretty = TRUE),
            con = dataFile)
}

#' Creates an active experiment given the critical files
#'
#' @param file The filename of the new analysis file (e.g., ~/Desktop/h_main.R)
#' @return NULL (creates the analysis file)
#' @importFrom magrittr %>%
#' @export
#' @examples
RecreateExperimentFiles <- function(file) {

 lines <- jsonlite::fromJSON(file)
 filenames <- file.path(dirname(file), c(lines$conditions$file,
                                         lines$events$files,
                                         paste0(lines$protocol$file, '.mpc')))
 contents <- list(lines$conditions$contents,
               lines$events$contents,
               lines$protocol$contents)
purrr::map2(contents, filenames, writeLines)
}

CreateRproj <- function(file) {

  lines <- c('Version: 1.0',
             ' ',
             'RestoreWorkspace: Default',
             'SaveWorkspace: Default',
             'AlwaysSaveHistory: Default',
             ' ',
             'EnableCodeIndexing: Yes',
             'UseSpacesForTab: Yes',
             'NumSpacesForTab: 2',
             'Encoding: UTF-8',
             ' ',
             'RnwWeave: Sweave',
             'LaTeX: pdfLaTeX')

  writeLines(lines, con = file)
}
