#' Creates an active experiment given the critical files
#'
#' @param name The name of the experiment (e.g., "Consistent Weber)
#' @param dropbox The dropbox path
#' @param conditionsFile The conditions file path
#' @param protocolFile The protocol file path
#' @param eventcodesFile The eventcodes file path
#' @return NULL (creates the experiment directory structure)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateActiveExperiment <- function(name, dropbox, conditionsFile, protocolFile, eventcodesFile=NULL){

  experiment = ExperimentID(basename(protocolFile))
  experimentFolderName = tolower(paste0(experiment, "_", gsub(" ", "_", name)))
  experimentFolder = file.path(dropbox, experimentFolderName)

  dir.create(file.path(experimentFolder, "data", "mpc"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "data", "json"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "analysis"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "manuscript"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "references"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "experiment"), recursive=TRUE)

  file.rename(eventcodesFile, file.path(dropbox, experimentFolderName, "experiment", basename(eventcodesFile)))
  file.rename(protocolFile, file.path(dropbox, experimentFolderName, "experiment", basename(protocolFile)))
  file.rename(conditionsFile, file.path(dropbox, experimentFolderName, "experiment", basename(conditionsFile)))

  CreateAnalysisMainFile(file.path(experimentFolder, "analysis", paste0(experiment, "_main.R")))
  CreateManuscriptMainFile(file.path(experimentFolder, "manuscript", paste0(experiment, "README.txt")))
}

#' Creates an active experiment given the critical files
#'
#' @param file The filename of the new analysis file (e.g., ~/Desktop/h_main.R)
#' @return NULL (creates the analysis file)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateAnalysisMainFile <- function(file){
  write(sprintf("# Name   : %s", basename(file)), file=file)
  write(sprintf("# Author : "), file=file, append=TRUE)
  write(sprintf("# Date   : "), file=file, append=TRUE)
  write(sprintf("# Purpose: "), file=file, append=TRUE)
  write(sprintf("# "), file=file, append=TRUE)
  write(sprintf("# "), file=file, append=TRUE)
  write(sprintf("# CHANGELOG "), file=file, append=TRUE)
  write(sprintf("# --------- "), file=file, append=TRUE)
  write(sprintf("# %s. Automatically generated by TSExperiment", format(Sys.Date(), "%m.%d.%Y")), file=file, append=TRUE)
  write(sprintf(" "), file=file, append=TRUE)
  write(sprintf("library(tidyverse)"), file=file, append=TRUE)
  write(sprintf("library(TSLib)"), file=file, append=TRUE)
}

#' Creates the manuscript's main Markdown file
#'
#' @param file The filename of the new manuscript file (e.g., ~/Dropbox/Active/h_consisten_weber/manuscript/h_main.md)
#' @return NULL (creates the markdown file)
#' @importFrom magrittr %>%
#' @export
#' @examples
CreateManuscriptMainFile <- function(file){
  write(sprintf("We strongly recommend you write your document in RMarkdown.
Use the R package papaja to knitr the document into an APA6 formatted PDF file"), file=file)
  return(NULL)
}
