# Name   : k_main.R
# Author :
# Date   :
# Purpose:
#
#
# CHANGELOG
# ---------
# 03.22.2017. Automatically generated by TSExperiment

library(tidyverse)
library(TSLib)
library(TSExperiment)

Data = ReadActiveJson()

left_reward = Data %>%
  filter(event == "On_Left_Feeder") %>%
  mutate(time = time - lag(time, default=0)) %>%
  filter(time <= 2000)


right_reward = Data %>%
  filter(event == "On_Right_Feeder") %>%
  mutate(time = time - lag(time, default=0)) %>%
  filter(time <= 2000)

ggplot() +
  coord_cartesian(xlim=c(0, 1000)) +
  geom_histogram(aes(x=time), binwidth=30, data=left_reward) +
  geom_histogram(aes(x=time), binwidth=30, data=right_reward) +
  facet_wrap(~subject)

left_nosepoke = Data %>%
  filter(event == "On_Left_Nosepoke") %>%
  group_by(subject) %>%
  mutate(cumulative_response = seq(1, n()))

right_nosepoke = Data %>%
  filter(event == "On_Right_Nosepoke") %>%
  group_by(subject) %>%
  mutate(cumulative_response = seq(1, n()))

ggplot() +
  geom_step(aes(x=time, y=cumulative_response), color="red", data=left_nosepoke) +
  geom_step(aes(x=time, y=cumulative_response), color="blue", data=right_nosepoke) +
  facet_wrap(~subject)

nosepokes = Data %>%
  filter(event %in% c("On_Left_Nosepoke", "On_Right_Nosepoke")) %>%
  group_by(subject) %>%
  mutate(bias = cumsum(ifelse(event=="On_Left_Nosepoke", 1, -1)))

nosepokes %>%
  filter(date == max(date)) %>%
  ggplot() +
  labs(x="Time (s)", y="Bias (left - right)") +
  coord_cartesian(ylim=c(-600, 600)) +
  theme(text=element_text(size=22), legend.position="none") +
  geom_step(aes(x=time, y=bias, group=subject, color=factor(subject)), size=1.3, data=nosepokes) +
  ggsave("./figures/Cumulative_bias.pdf", dpi=300, width=6, height=4)
