PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box2.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box3.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box4.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box5.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box6.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box7.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetB_Box8.mac 
START BOXES 1 2 3 4 5 6 7 8
