PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box1.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box2.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box3.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box4.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box5.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box6.mac 
PLAYMACRO C:\Users\gallistellab\Dropbox\Active\macros\submacs\CabinetA_Box8.mac 
START BOXES 1 2 3 4 5 6 7 8
