library(TSExperiment)

CreateAnalysisMainFile <- function(file){
  write(sprintf("# Name   : %s", basename(file)), file=file)
  write(sprintf("# Author : "), file=file, append=TRUE)
  write(sprintf("# Date   : "), file=file, append=TRUE)
  write(sprintf("# Purpose: "), file=file, append=TRUE)
  write(sprintf("# "), file=file, append=TRUE)
  write(sprintf("# "), file=file, append=TRUE)
  write(sprintf("# CHANGELOG "), file=file, append=TRUE)
  write(sprintf("# --------- "), file=file, append=TRUE)
  write(sprintf("# %s. Automatically generated by TSExperiment", format(Sys.Date(), "%m.%d.%Y")), file=file, append=TRUE)
  write(sprintf(" "), file=file, append=TRUE)
  write(sprintf("library(tidyverse)"), file=file, append=TRUE)
  write(sprintf("library(TSLib)"), file=file, append=TRUE)
}


BeginExperiment <- function(){

  dropbox = file.path("~", "Desktop") #DropBoxPaths()$LocalActiveExperimentPath

  # What is the name of your experiment?
  name = "Consistent Weber"

  conditionsFile = file.choose()
  experiment = ExperimentID(basename(conditionsFile))
  experimentFolderName = paste0(experiment, "_", gsub(" ", "_", name))

  #Are the protocol and eventcodes file in the same directory?
  all_in_directory = TRUE
  if (all_in_directory){
    protocolFile = Sys.glob(file.path(dirname(conditionsFile), paste0(experiment, "_protocol.mpc")))
    eventcodesFile = Sys.glob(file.path(dirname(conditionsFile), paste0(experiment, "_eventcodes.csv")))
  } else{
    protocolFile = file.choose()
    eventcodesFile = file.choose()
  }
}

CreateActiveExperiment <- function(conditionsFile, protocolFile, eventcodesFile=NULL){

  experimentFolder = file.path(dropbox, experimentFolderName)
  dir.create(file.path(experimentFolder, "data", "mpc"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "data", "json"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "analysis"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "manuscript"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "references"), recursive=TRUE)
  dir.create(file.path(experimentFolder, "experiment"), recursive=TRUE)

  file.rename(conditionsFile, file.path(dropbox, experimentFolderName, "experiment", basename(conditionsFile)))
  file.rename(protocolFile, file.path(dropbox, experimentFolderName, "experiment", basename(protocolFile)))
  file.rename(eventcodesFile, file.path(dropbox, experimentFolderName, "experiment", basename(eventcodesFile)))

  AnalysisFileName = file.path(experimentFolder, "analysis", paste0(experiment, "_main.R"))
}
